### ISSUE TITLE
regression in 14.1.2: wrong popup position with elix-popup-button

### ISSUE THREAD

**Issue by geonanorch** [elix/elix#163]
Hi there.

A regression occurred between 14.1.1 and 14.1.2: positioning of the popup by `elix-popup-button` no longer works correctly.

I have a button positioned at the right of the page, the popup should therefore expand left from the right side of the page (behavior with 14.1.1) but now it starts at the right side of the page and expands right, overflowing outside the page (14.1.2).

If the bug is not obvious let me know and I'll work on providing a reproducer.

**Comment by JanMiksovsky** [comment]
Thanks for reporting the problem. We've been doing a lot of work on popups, so it's not surprising to hear that you've hit a regression.

I can see at least one problem, but I'm not sure it's the one you describe. A repro case would be helpful, but a screenshot showing the problem and the relevant HTML/CSS would also work.

**Comment by JanMiksovsky** [comment]
I've pushed a fix to #main for the popup alignment issue I could see.

If you have a chance to try that out, please let me know whether it addresses your issue or not. I'm still doing some cleanup work in that area, and it'd be nice to know whether more work is necessary in this area before moving on to other things.

**Comment by geonanorch** [comment]
Damned, you were faster ;-) 
But as the issue occurs with the latest commit I can still make it up, here hopefully [a reproducer](https://plnkr.co/plunk/gWpP3GhySCptwpms):
```
    <div style="display: flex; flex-direction: row; padding: 0 10px">
      <span style="flex: 1">TITLE</span>
      <span style="flex:none; float:right">
        <elix-popup-button>
          <a slot="source">BUTTON</a>
          <div style="width: 12rem;">
            <div >ITEM 1</div >
            <div >LONG ITEM 2</div >
            <div >VERY LONG ITEM 3</div >
          </div>
        </elix-popup-button>
      </span>
    </div>
```
I first though that the flex was causing trouble, but you can comment out `display: flex` and still get the same result with the `float: right` style.
The width of the popup is fine.

**Comment by JanMiksovsky** [comment]
Thanks for the repro case!

This fix won't be released to npm for a little while (a few weeks?). When I fork your repro case and [use what's now on #main](https://plnkr.co/edit/NgfOQKJXuZrVnlBY), it looks like the popup flips to be right-aligned as expected.

If I'm missing something, please let me know if you're still seeing something that looks wrong.

**Comment by geonanorch** [comment]
My mistake, out of habit I went for `master` instead of `main`. I can confirm that our issue is fixed with `main`.
Thanks a lot and my apologies for the unnecessary second round.
